services:
  app:
    image: asset-manager:latest
    build:
      context:      .
      dockerfile:   Dockerfile
      # extra_hosts:
      #  -  "npm-registry.srv.axiomptk=10.2.10.2"
    environment:
      TWOWOLVES_OIDC_AUTHORITY: "${VITE_OIDC_AUTHORITY}"
      TWOWOLVES_OIDC_CLIENT_ID: "${VITE_OIDC_CLIENT_ID}"
      TWOWOLVES_OIDC_REDIRECT_URI: "${VITE_OIDC_REDIRECT_URI}"
      TWOWOLVES_OIDC_POST_LOGOUT_REDIRECT_URI: "${VITE_OIDC_POST_LOGOUT_REDIRECT_URI}"
      TWOWOLVES_OIDC_SCOPE: "${VITE_OIDC_SCOPE}"
      TWOWOLVES_APPS_API_BASE_URL: "${VITE_APPS_API_BASE_URL}"
    ports:
    - "9797:80"
