services:
  app:
    image: asset-manager:latest
    build:
      context:      .
      dockerfile:   Dockerfile
      # extra_hosts:
      #  -  "npm-registry.srv.axiomptk=10.2.10.2"
    ports:
    - "9797:80"
